# Generated by Django 4.0.4 on 2022-09-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facebookId', models.IntegerField()),
                ('sessionId', models.CharField(max_length=255)),
            ],
        ),
    ]
